# Generated by Django 3.2.5 on 2022-04-28 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='classes',
            field=models.ManyToManyField(blank=True, related_name='students', to='main.Classroom'),
        ),
    ]
