# Generated by Django 3.2.5 on 2022-05-10 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_student_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='building',
            field=models.CharField(default='- Building -', max_length=64),
        ),
        migrations.AddField(
            model_name='classroom',
            name='room',
            field=models.CharField(default='- Room -', max_length=64),
        ),
        migrations.AddField(
            model_name='classroom',
            name='teacher',
            field=models.CharField(default='- Teacher -', max_length=64),
        ),
    ]
